'use strict';
console.log('HOMEWORK3 HOMEWORK3 HOMEWORK3 HOMEWORK3');

// HOMEWORK3 HOMEWORK3 HOMEWORK3 HOMEWORK3
// HOMEWORK3 HOMEWORK3 HOMEWORK3 HOMEWORK3
// HOMEWORK3 HOMEWORK3 HOMEWORK3 HOMEWORK3
// HOMEWORK3 HOMEWORK3 HOMEWORK3 HOMEWORK3

let pathURL = {
  protocol: window.location.protocol,
  hostname: window.location.hostname,
  path: window.location.href,
  searches: window.location.search.split('&'),
  hash: window.location.hash,
}

// HOMEWORK3 HOMEWORK3 HOMEWORK3 HOMEWORK3
// HOMEWORK3 HOMEWORK3 HOMEWORK3 HOMEWORK3
// HOMEWORK3 HOMEWORK3 HOMEWORK3 HOMEWORK3
// HOMEWORK3 HOMEWORK3 HOMEWORK3 HOMEWORK3